# Generated by Django 4.0.2 on 2022-02-15 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_createrd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
